name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Verify dist files
        run: |
          # Store current dist files
          mv dist dist-current
          
          # Build fresh dist files
          npm run build
          
          # Compare if there are any differences
          if ! diff -r dist dist-current > /dev/null 2>&1; then
            echo "::error::Dist files are not up to date. Please run 'npm run build' and commit the changes."
            exit 1
          fi
          
          # Restore original dist files
          rm -rf dist
          mv dist-current dist
        
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Generate release notes from commits since last release
          RELEASE_NOTES=$(git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s%n")
          
          # Create GitHub release
          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "$RELEASE_NOTES" \
            --draft=false
